# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Brèves
    url: post
    weight: 20
  - name: Événements
    url: event
    weight: 40
  - name: Contact
    url: contact
    weight: 999
  - name: Présentation
    url: presentation
    weight: 45
  - name: Les laboratoires
    url: laboratoires
    weight: 46
  - name: Listes de diffusion
    url: listes
    weight: 47

  - identifier: gts
    name: Les groupes de travail
    weight: 50
  - parent: gts
    name: GT-AS
    url: gts/gt-as
    weight: 50
  - parent: gts
    name: GT-GDMM
    url: gts/gt-gdmm
    weight: 51
  - parent: gts
    name: GT-MG
    url: gts/gt-mg
    weight: 52
  - parent: gts
    name: GT-Rendu
    url: gts/gt-rendu
    weight: 53
  - parent: gts
    name: GT-RV
    url: gts/gt-rv
    weight: 54
  - parent: gts
    name: GT-Visu
    url: gts/gt-visu
    weight: 55


  - name: Actions et journées
    url: actions
    weight: 70
  - name: Club  industriel
    url: club-industriel
    weight: 70
